main:
    random_seed: 0
    saved_dir: '/home/tony/Incremental_Learning/models/icarl/'

# load:
#     loaded_path: 'path/to/checkpoint.pth'
#     task_complete: 0

learner:
    name: 'ICaRLLearner'
    kwargs:
        total_num_class: 100
        class_per_task: 10
        exampler_size: 2000
        chosen_order: 0

dataset:
    name: 'IncrementalDataset'
    kwargs:
        data_dir: '/home/tony/datasets/CIFAR_preprocessed'
        csv_name: 'CIFAR_split.csv'
        transforms:
        augments:

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 128
        valid:
            batch_size: 128
        test:
            batch_size: 128
        shuffle: true
        num_workers: 8

net:
    name: 'ICaRLNet'
    kwargs:
        convnet_type: "resnet34"
        use_bias: False
        init: "kaiming"
        use_multi_fc: False
        pretrained: True

losses:
    - name: 'MyBCELoss'
      weight: 1.0

metrics:
    - name: 'Accuracy'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 2.0

lr_scheduler:
    name: 'MultiStepLR'
    kwargs:
        milestones: [49, 63]
        gamma: 0.2

logger:
    name: 'ICaRLLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'loss'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'ICaRLTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 70
        valid_freq: 1
