main:
    random_seed: 0
    saved_dir: '/home/peter850706/MedicalPro/models/acdc_seg/from_scratch/tmp'

learner:
    name: 'ICaRLLearner'
    kwargs:
        total_num_class: 100
        class_per_task: 20
        chosen_order: 0

dataset:
    name: 'IncrementalDataset'
    kwargs:
        data_dir: '/home/tony/datasets/CIFAR_preprocessed'
        csv_name: 'CIFAR_split.csv'
        transforms:
        augments:

dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 10
        valid:
            batch_size: 10
        test:
            batch_size: 10
        shuffle: true
        num_workers: 8

net:
    name: 'ModelsGenesisSegNet'
    kwargs:
        in_channels: 1
        out_channels: 4

losses:
    - name: 'CrossEntropyLossWrapper'
      alias: 'cross_entropy_loss'
    - name: 'DiceLoss'
      alias: 'dice_loss'

metrics:
    - name: 'Dice'
      alias: 'dice'

optimizer:
    name: 'Adam'
    kwargs:
        lr: 0.001

logger:
    name: 'AcdcSegLogger'

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'min'
        target: 'loss'
        saved_freq: 1000
        early_stop: 0

trainer:
    name: 'AcdcSegTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 10000
        valid_freq: 10
